# Yttrium

spacing         = 1
padding         = 0
hide_ascii      = false
prefer_small_ascii = true
separator       = "Î»"
key_color       = "#7156a8"
separator_color = "White"


[palette]
type = "Dark"
visible = true
glyph = " â¬¤ "

[bar]
glyph           = "+"
symbol_open     = 'â€‹' #funny 0 width space
symbol_close    = 'â€‹'
hide_delimiters = false
visible         = true

[box]
title 	        = " yttrium "
border          = "round"
visible         = true

[box.inner_margin]
x               = 1
y               = 1

[custom_ascii]
color 			= "#7156a8"
path 			= "C:\\Users\\Giacomo\\AppData\\Roaming\\macchina\\themes\\terminal_logo_alt.txt"

[randomize]
key_color       = false
separator_color = false

# [keys]
# host="ğŸ‘¨ğŸ»â€ğŸ’»"
# machine="âš™ï¸"
# kernel="ğŸŒ½"
# packages="ğŸ“¦"
# cpu="ğŸ’½"
# memory="ğŸ"
# uptime="âŒ›"
# os="ğŸ–¥ï¸"
[keys]
host="host"
machine="machine"
kernel="kernel"
packages="packages"
cpu="cpu"
memory="memory"
uptime="uptime"
os="os"